  
version: '3'

services:
  scrapper:
    image: scrapper:1.0
    container_name: scrapper
    environment:
      - NUMBER_OF_REQUESTS=200
      - SCRAPE_PAGES=1
      - CITY=Lahore
      - TYPE=Houses_Property
      - SLEEP_INTERVAL=10
      - S3_ENDPOINT=172.18.0.5:9000
      - S3_USER=user
      - S3_PASSWORD=password
    tty: true
    networks:
      datapipeline:
        ipv4_address: 172.18.0.4

  minio:
    image: quay.io/minio/minio:RELEASE.2022-11-26T22-43-32Z.fips
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ACCESS_KEY_FILE: /run/secrets/minio_user
      MINIO_SECRET_KEY_FILE: /run/secrets/minio_password
    secrets:
      - minio_user
      - minio_password
    command: server /data --console-address ":9090"
    networks:
      datapipeline:
        ipv4_address: 172.18.0.5

secrets:
  minio_user:
    file: ./secrets/minio_user.txt
  minio_password:
    file: ./secrets/minio_password.txt

volumes:
  minio_storage: {}

networks:
  datapipeline:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"