FROM docker.io/condaforge/mambaforge@sha256:a119fe148b8a276397cb7423797f8ee82670e64b071dc39c918b6c3513bd0174
RUN bin/bash

ENV NUMBER_OF_REQUESTS = ''
ENV SCRAPE_PAGES = ''
ENV CITY = ''
ENV TYPE = ''
ENV SLEEP_INTERVAL =  ''

## Creating the new conda environment with the desired packages using mamba
WORKDIR /opt
COPY environment.yml .
RUN mamba env create -f environment.yml
RUN echo "conda activate real_estate" >> ~/.bashrc

# Install base utilities
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y build-essential  && \
    apt-get install -yq curl wget jq vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# COPYING SCRAPPER FILES
COPY scrapper/scrapper_package /opt/scrapper/scrapper_package
COPY scrapper/main.py /opt/scrapper/main.py

# STARTING THE SCRAPPER WITH THE DESIRED CONFIGURATION
ENTRYPOINT ["/opt/conda/envs/real_estate/bin/python","-u", "/opt/scrapper/main.py"]
